run:
  timeout: 10m
  tests: true
issues:
  exclude-dirs-use-default: false
linters:
  enable-all: false
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - typecheck
    - stylecheck
    - tagliatelle
  disable:
    - unused
    - deadcode
  exclusions:
    paths:
      - vendor$
      - third_party$
      - hack