version: "2"
run:
  timeout: 10m
  tests: true
linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - tagliatelle
  disable:
    - unused
  exclusions:
    paths:
      - vendor$
      - third_party$
      - hack