version: 1.54.2
run:
  timeout: 10m
  skip-dirs:
    - vendor$
    - third_party$
    - hack
  tests: true
  skip-dirs-use-default: false
linters:
  enable-all: false
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - typecheck
    # - varcheck # deprecated - https://github.com/golangci/golangci-lint/issues/1841
    - stylecheck
    - tagliatelle
  disable:
    - unused
    - deadcode
